class MyTexts {
  static MyTexts? _instance;
  static MyTexts get instance {
    _instance ??= MyTexts._init();
    return _instance!;
  }

  MyTexts._init();

  final String logoImage = "lib/assets/images/hermod.png";
  final String getStartedText = "Sadece bir takı mağazası değil fikirlerin takıya dönüştüğü yaratıcılık atölyesi";
  final String getStartedButtonText = "Hadi başlayalım";
  final String logInText = "Giriş yap";
  final String emailText = "Email";
  final String passwordText = "Şifre";
  final String confirmPasswordText = "Tekrar Şifre";
  final String orLoginWithText = "ya da ";
  final String orSignUpWithText = "ya da ";
  final String loginWithFaceText = "Facebook ile giriş yap";
  final String loginWithGoogleText = "Google ile giriş yap";
  final String signUpWithFaceText = "Facebook ile üye ol";
  final String signUpWithGoogleText = "Google ile üye ol";
  final String withGoogleImageText = "lib/assets/images/googlelogo.png";
  final String withFaceImageText = "lib/assets/images/logoface.png";
  final String profileImageText = "lib/assets/images/profile.jpg";
  final String dontHaveAccountText = "Hesabın yoksa";
  final String alreadyHaveAccountText = "Zaten hesabın var mı?";
  final String signUpText = "Üye ol";
  final String wrongMessage = "Bir şeyler ters gitti";
  final String defaultCategoryId = "6zVmOOjixUhKYifadNXl";
  final String searchText = "Ara";
  final String title = "Hermod Jewelery";
  final String favoritesText = "Favorilerim";
  final String basketsText = "Sepetim";
  final String addBasketText = "Sepete ekle";
  final String deleteText = "Sil";
  final String siparisiTamamlaText = "Siparişi Tamamla";
  final String fotografYukleText = "FOTOĞRAF YÜKLE";
  final String kameradanCekText = "KAMERADAN ÇEK";
  final String arananUrunBulunamadiText = "Aranan ürün bulunamadı...";
  final String userNotFoundText = "Kullanıcı bulunamadı...";
  final String locationText = "Adreslerim";
  final String myBasketsText = "Siparişlerim";
  final String myCardsText = "Kayıtlı kartlarım";
  final String helpText = "Yardım ve Destek";
  final String settingsText = "Ayarlar";
  final String logOutText = "Çıkış yap";
  final String carosuelImage = "lib/assets/images/BANNER.png";
  final String myFontFamily = "DejaVu Serif";
  final String helloText = "Merhaba , ";
  final String addressText = 'Konum';
  final String addAddressText = "Adresi ekle";
  final String name = "Ad";
  final String surname = "Soyad";
  final String city = "İl";
  final String district = "İlçe";
  final String adres = "Adres";
  final String goToPayText = "Ödemeye geç";
  final String deleteToAddress = "Adresi silmek istiyor musunuz?";
  final String yesText = "Evet";
  final String myAddressText = "Adreslerim";
  final String odemeyiTamamlaText = "Ödemeyi tamamla";
  final String saveCardText = "Kartı kaydet";
  final String cardSuccessSaveText = 'Card saved successfully';
  final String savedCardText = "Kayıtlı kartlarım";
  final String liveHelpText = "İade işlemleri için , C a n l ı Y a r d ı m ile iletişime geçebilirsin";
  final String liveHelp = "Canlı Yardım";
  final String helpTimeText = "Her gün 09:00 - 23:00";
  final String questionsText = "Sıkça Sorulan Sorular";
  final String answerText = "Sorularının cevaplarına buradan ulaşabilirsin.";
  final String iletisimeGececegizText = "Siparişinizle ve oluşturmuş olduğunuz taleplerle ilgili 850'li bir numaradan iletişime geçeceğiz. ";
  final String orderTitleText = "Sipariş ID : #576404";
  final String orderSubtitleText = "Sipariş zamanı: 6.35 PM | 24 Haziran 2024";
  final String orderSitiationTextOne = "Teslim edildi.";
  final String orderSitiationTextTwo = "İptal edildi.";
  final String orderSitiationTextThree = "Hazırlanıyor...";
  final String kisiselBilgilerimiGuncelleText = "Kişisel Bilgilerimi Güncelle";
  final String epostaAdresimiGuncelleText = "E-posta Adresimi Güncelle";
  final String iletisimTercihlerimiGuncelleText = "İletişim Tercihlerimi Güncelle";
  final String hesabimiSilText = "Hesabımı Sil";
  final String favoriBosText = "Favorilerinizde ürün yok.";
  final String sepetBosText = "Sepetinizde ürün bulunmamaktadır.";
  final String adresBosText = "Adres ekleyiniz...";
  final String kartBosText = "Kayıtlı kartınız bulunmamaktadır.";
  final String geminiTitle = "Gemini Chat";
  final String geminiProfileImage = "https://seeklogo.com/images/G/google-gemini-logo-A5787B2669-seeklogo.com.png";
}
